// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArnAfMsQx8OcKn-AkjpDjDqxV8vOdcLak',
    appId: '1:120276148387:web:97ae024656bec7c3b7df16',
    messagingSenderId: '120276148387',
    projectId: 'tt-flutter-airdrop-service',
    authDomain: 'tt-flutter-airdrop-service.firebaseapp.com',
    storageBucket: 'tt-flutter-airdrop-service.firebasestorage.app',
    measurementId: 'G-RWY7E78P0Q',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdXJKJ7TYQ5S2csZqapp2geKOXbFqhTAc',
    appId: '1:120276148387:ios:50c73c3a50372811b7df16',
    messagingSenderId: '120276148387',
    projectId: 'tt-flutter-airdrop-service',
    storageBucket: 'tt-flutter-airdrop-service.firebasestorage.app',
    iosBundleId: 'com.example.ttFlutterAirdropService',
  );

}